import type { ThemeConfig } from 'antd'
import { theme } from 'antd'

// Couleurs CEM (Culte d'Enfants de Melen)
const CEM_GREEN   = '#1A6B1A'
const CEM_DARK    = '#0F4A0F'
const CEM_YELLOW  = '#F5C400'
const FONT_FAMILY = "'Montserrat', system-ui, sans-serif"

export const lightTheme: ThemeConfig = {
  algorithm: theme.defaultAlgorithm,
  token: {
    colorPrimary:        CEM_GREEN,
    colorSuccess:        '#10B981',
    colorError:          '#EF4444',
    colorInfo:           '#3B82F6',
    colorLink:           CEM_GREEN,
    colorLinkHover:      CEM_DARK,
    colorTextBase:       '#0F172A',
    colorBgBase:         '#FFFFFF',
    colorBgLayout:       '#F8FAF8',
    colorBgContainer:    '#FFFFFF',
    colorBgElevated:     '#FFFFFF',
    colorBorder:         '#E2E8F0',
    colorBorderSecondary:'#F1F5F9',
    borderRadius:        10,
    borderRadiusLG:      20,
    borderRadiusSM:      8,
    fontFamily:          FONT_FAMILY,
    fontSize:            14,
    fontSizeHeading3:    24,
    fontWeightStrong:    600,
    lineHeight:          1.5,
    controlHeight:       44,
    controlHeightLG:     48,
    controlHeightSM:     36,
    controlOutline:      `${CEM_GREEN}30`,
    boxShadow:           '0 4px 16px rgba(15, 23, 42, 0.08)',
    boxShadowSecondary:  '0 12px 32px rgba(15, 23, 42, 0.12)',
    // Couleur jaune CEM comme couleur secondaire via les CSS vars
    colorWarning:        CEM_YELLOW,
  },
  components: {
    Button: {
      primaryColor:        '#FFFFFF',
      defaultBorderColor:  CEM_GREEN,
      defaultColor:        CEM_GREEN,
      fontWeight:          600,
      paddingInline:       18,
    },
    Menu: {
      itemBg:              'transparent',
      itemColor:           'rgba(255,255,255,0.7)',
      itemHoverColor:      '#FFFFFF',
      itemSelectedColor:   CEM_DARK,
      itemSelectedBg:      CEM_YELLOW,
      itemActiveBg:        CEM_YELLOW,
      subMenuItemBg:       'transparent',
      darkItemColor:       'rgba(255,255,255,0.7)',
      darkItemHoverColor:  '#FFFFFF',
      darkItemSelectedColor: CEM_DARK,
      darkItemSelectedBg:  CEM_YELLOW,
    },
    Input: {
      activeBorderColor:   CEM_GREEN,
      hoverBorderColor:    CEM_GREEN,
      activeShadow:        `0 0 0 2px ${CEM_GREEN}30`,
    },
    Select: {
      optionSelectedBg:    '#E8F5E8',
      optionActiveBg:      '#F0FDF4',
    },
    Table: {
      headerBg:            '#F8FAFC',
      headerColor:         '#334155',
      rowHoverBg:          '#F0FDF4',
      rowSelectedBg:       '#E8F5E8',
      rowSelectedHoverBg:  '#DCF0DC',
      borderColor:         '#E2E8F0',
      cellPaddingBlock:    14,
      cellPaddingInline:   16,
      headerBorderRadius:  12,
    },
    Card: {
      headerBg:            '#FFFFFF',
      headerFontSize:      16,
      headerHeight:        56,
      bodyPadding:         24,
      headerPadding:       24,
      actionsBg:           '#FFFFFF',
      extraColor:          '#64748B',
    },
    Layout: {
      bodyBg:              '#F8FAF8',
      headerBg:            '#FFFFFF',
      headerColor:         '#0F172A',
      siderBg:             '#052005',
      footerBg:            '#F8FAF8',
      triggerBg:           CEM_DARK,
      triggerColor:        '#FFFFFF',
    },
    Drawer: {
      footerPaddingBlock:  16,
      footerPaddingInline: 24,
    },
    Modal: {
      borderRadiusLG:      20,
      headerBg:            '#FFFFFF',
      contentBg:           '#FFFFFF',
      footerBg:            '#FFFFFF',
      titleColor:          '#0F172A',
      titleFontSize:       18,
    },
    Form: {
      labelColor:          '#334155',
      labelFontSize:       14,
      labelRequiredMarkColor: '#DC2626',
      itemMarginBottom:    20,
      verticalLabelPadding: '0 0 6px',
    },
    Tabs: {
      itemColor:           '#64748B',
      itemSelectedColor:   CEM_GREEN,
      itemHoverColor:      CEM_DARK,
      inkBarColor:         CEM_GREEN,
      horizontalItemPadding: '12px 4px',
    },
    Pagination: {
      itemActiveBg:        '#E8F5E8',
      itemActiveColor:     CEM_DARK,
      itemActiveColorHover:CEM_GREEN,
      itemSize:            36,
      itemSizeSM:          28,
    },
    Alert: {
      defaultPadding:      '12px 16px',
      withDescriptionPadding: '16px 20px',
      withDescriptionIconSize: 22,
    },
    Result: {
      titleFontSize:       24,
      subtitleFontSize:    15,
      iconFontSize:        64,
      extraMargin:         '28px 0 0',
    },
    Statistic: {
      titleFontSize:       14,
      contentFontSize:     28,
    },
    Steps: {
      iconSize:            36,
      iconSizeSM:          28,
      iconFontSize:        16,
      dotSize:             10,
      dotCurrentSize:      12,
      navArrowColor:       '#94A3B8',
    },
    Upload: {
      actionsColor:        CEM_GREEN,
      pictureCardSize:     112,
    },
    DatePicker: {
      activeBorderColor:   CEM_GREEN,
      hoverBorderColor:    CEM_GREEN,
      activeShadow:        `0 0 0 2px ${CEM_GREEN}30`,
      cellHoverBg:         '#F0FDF4',
      cellActiveWithRangeBg: '#E8F5E8',
      cellHoverWithRangeBg: '#DCF0DC',
      cellRangeBorderColor:CEM_GREEN,
      cellHeight:          28,
    },
    Dropdown: {
      paddingBlock:        8,
    },
    Badge: {
      indicatorHeight:     20,
      indicatorHeightSM:   16,
      dotSize:             8,
      statusSize:          8,
      textFontWeight:      600,
    },
    Progress: {
      defaultColor:        CEM_GREEN,
      remainingColor:      '#E2E8F0',
      circleTextColor:     '#0F172A',
      lineBorderRadius:    999,
    },
    Tag: {
      borderRadiusSM:      20,
    },
    Notification: {
      width:               320,
    },
  },
}

export const darkTheme: ThemeConfig = {
  algorithm: theme.darkAlgorithm,
  token: {
    colorPrimary:        CEM_GREEN,
    colorSuccess:        '#10B981',
    colorWarning:        CEM_YELLOW,
    colorError:          '#EF4444',
    colorInfo:           '#3B82F6',
    colorLink:           '#4ADE80',
    colorLinkHover:      '#86EFAC',
    colorBgLayout:       '#071207',
    colorBgContainer:    '#102010',
    colorBgElevated:     '#172A17',
    colorBorder:         '#334B33',
    colorBorderSecondary:'#263B26',
    borderRadius:        10,
    borderRadiusLG:      20,
    borderRadiusSM:      8,
    fontFamily:          FONT_FAMILY,
    fontSize:            14,
    fontSizeHeading3:    24,
    fontWeightStrong:    600,
    lineHeight:          1.5,
    controlHeight:       44,
    controlHeightLG:     48,
    controlHeightSM:     36,
    controlOutline:      'rgba(74, 222, 128, 0.24)',
    boxShadow:           '0 4px 16px rgba(0, 0, 0, 0.28)',
    boxShadowSecondary:  '0 12px 32px rgba(0, 0, 0, 0.4)',
  },
  components: {
    Button: {
      primaryColor: '#FFFFFF',
      fontWeight:   600,
      paddingInline: 18,
    },
    Menu: {
      itemBg:              'transparent',
      itemColor:           'rgba(255,255,255,0.7)',
      itemHoverColor:      '#FFFFFF',
      itemSelectedColor:   CEM_DARK,
      itemSelectedBg:      CEM_YELLOW,
      darkItemSelectedBg:  CEM_YELLOW,
      darkItemSelectedColor: CEM_DARK,
    },
    Input: {
      activeBorderColor:   CEM_GREEN,
      hoverBorderColor:    CEM_GREEN,
      activeShadow:        `0 0 0 2px ${CEM_GREEN}30`,
    },
    Select: {
      optionSelectedBg:    '#1A3D1A',
    },
    Table: {
      headerBg:            '#1E293B',
      headerColor:         '#E2E8F0',
      rowHoverBg:          '#1A3D1A',
      rowSelectedBg:       '#214821',
      rowSelectedHoverBg:  '#285528',
      borderColor:         '#334B33',
      cellPaddingBlock:    14,
      cellPaddingInline:   16,
      headerBorderRadius:  12,
    },
    Card: {
      headerBg:            '#102010',
      headerFontSize:      16,
      headerHeight:        56,
      bodyPadding:         24,
      headerPadding:       24,
      actionsBg:           '#102010',
      extraColor:          '#94A3B8',
    },
    Layout: {
      bodyBg:              '#071207',
      headerBg:            '#102010',
      headerColor:         '#F8FAFC',
      siderBg:             '#031003',
      footerBg:            '#071207',
      triggerBg:           CEM_DARK,
      triggerColor:        '#FFFFFF',
    },
    Drawer: {
      footerPaddingBlock:  16,
      footerPaddingInline: 24,
    },
    Modal: {
      borderRadiusLG:      20,
      headerBg:            '#102010',
      contentBg:           '#102010',
      footerBg:            '#102010',
      titleColor:          '#F8FAFC',
      titleFontSize:       18,
    },
    Form: {
      labelColor:          '#CBD5E1',
      labelFontSize:       14,
      labelRequiredMarkColor: '#F87171',
      itemMarginBottom:    20,
      verticalLabelPadding: '0 0 6px',
    },
    Tabs: {
      itemColor:           '#94A3B8',
      itemSelectedColor:   '#4ADE80',
      itemHoverColor:      '#86EFAC',
      inkBarColor:         '#4ADE80',
      horizontalItemPadding: '12px 4px',
    },
    Pagination: {
      itemActiveBg:        '#1A3D1A',
      itemActiveColor:     '#86EFAC',
      itemActiveColorHover:'#4ADE80',
      itemSize:            36,
      itemSizeSM:          28,
    },
    Alert: {
      defaultPadding:      '12px 16px',
      withDescriptionPadding: '16px 20px',
      withDescriptionIconSize: 22,
    },
    Result: {
      titleFontSize:       24,
      subtitleFontSize:    15,
      iconFontSize:        64,
      extraMargin:         '28px 0 0',
    },
    Statistic: {
      titleFontSize:       14,
      contentFontSize:     28,
    },
    Steps: {
      iconSize:            36,
      iconSizeSM:          28,
      iconFontSize:        16,
      dotSize:             10,
      dotCurrentSize:      12,
      navArrowColor:       '#64748B',
    },
    Upload: {
      actionsColor:        '#4ADE80',
      pictureCardSize:     112,
    },
    DatePicker: {
      activeBorderColor:   '#4ADE80',
      hoverBorderColor:    '#4ADE80',
      activeShadow:        '0 0 0 2px rgba(74, 222, 128, 0.24)',
      cellHoverBg:         '#1A3D1A',
      cellActiveWithRangeBg: '#214821',
      cellHoverWithRangeBg: '#285528',
      cellRangeBorderColor:'#4ADE80',
      cellHeight:          28,
    },
    Dropdown: {
      paddingBlock:        8,
    },
    Badge: {
      indicatorHeight:     20,
      indicatorHeightSM:   16,
      dotSize:             8,
      statusSize:          8,
      textFontWeight:      600,
    },
    Progress: {
      defaultColor:        '#4ADE80',
      remainingColor:      '#334B33',
      circleTextColor:     '#F8FAFC',
      lineBorderRadius:    999,
    },
    Notification: {
      width: 320,
    },
  },
}
