import type { ThemeConfig } from 'antd'
import { theme } from 'antd'

// Couleurs CEM (Culte d'Enfants de Melen)
const CEM_GREEN   = '#1A6B1A'
const CEM_DARK    = '#0F4A0F'
const CEM_YELLOW  = '#F5C400'
const FONT_FAMILY = "'Inter', system-ui, sans-serif"

export const lightTheme: ThemeConfig = {
  algorithm: theme.defaultAlgorithm,
  token: {
    colorPrimary:        CEM_GREEN,
    colorSuccess:        '#10B981',
    colorError:          '#EF4444',
    colorInfo:           '#3B82F6',
    colorLink:           CEM_GREEN,
    colorLinkHover:      CEM_DARK,
    colorTextBase:       '#0F172A',
    colorBgBase:         '#FFFFFF',
    colorBgLayout:       '#F8FAF8',
    colorBgContainer:    '#FFFFFF',
    colorBgElevated:     '#FFFFFF',
    colorBorder:         '#E2E8F0',
    colorBorderSecondary:'#F1F5F9',
    borderRadius:        10,
    borderRadiusLG:      20,
    borderRadiusSM:      8,
    fontFamily:          FONT_FAMILY,
    fontSize:            14,
    fontSizeHeading3:    24,
    fontWeightStrong:    600,
    lineHeight:          1.5,
    controlHeight:       44,
    controlHeightLG:     48,
    controlHeightSM:     36,
    controlOutline:      `${CEM_GREEN}30`,
    boxShadow:           '0 4px 16px rgba(15, 23, 42, 0.08)',
    boxShadowSecondary:  '0 12px 32px rgba(15, 23, 42, 0.12)',
    // Couleur jaune CEM comme couleur secondaire via les CSS vars
    colorWarning:        CEM_YELLOW,
  },
  components: {
    Button: {
      primaryColor:        '#FFFFFF',
      defaultBorderColor:  CEM_GREEN,
      defaultColor:        CEM_GREEN,
      fontWeight:          600,
      paddingInline:       18,
    },
    Menu: {
      itemBg:              'transparent',
      itemColor:           'rgba(255,255,255,0.7)',
      itemHoverColor:      '#FFFFFF',
      itemSelectedColor:   CEM_DARK,
      itemSelectedBg:      CEM_YELLOW,
      itemActiveBg:        CEM_YELLOW,
      subMenuItemBg:       'transparent',
      darkItemColor:       'rgba(255,255,255,0.7)',
      darkItemHoverColor:  '#FFFFFF',
      darkItemSelectedColor: CEM_DARK,
      darkItemSelectedBg:  CEM_YELLOW,
    },
    Input: {
      activeBorderColor:   CEM_GREEN,
      hoverBorderColor:    CEM_GREEN,
      activeShadow:        `0 0 0 2px ${CEM_GREEN}30`,
    },
    Select: {
      optionSelectedBg:    '#E8F5E8',
      optionActiveBg:      '#F0FDF4',
    },
    Table: {
      headerBg:            '#F8FAFC',
      headerColor:         '#334155',
      rowHoverBg:          '#F0FDF4',
      rowSelectedBg:       '#E8F5E8',
      rowSelectedHoverBg:  '#DCF0DC',
      borderColor:         '#E2E8F0',
      cellPaddingBlock:    14,
      cellPaddingInline:   16,
      headerBorderRadius:  12,
    },
    Card: {
      headerBg:            '#FFFFFF',
      headerFontSize:      16,
      headerHeight:        56,
      bodyPadding:         24,
      headerPadding:       24,
      actionsBg:           '#FFFFFF',
      extraColor:          '#64748B',
    },
    Layout: {
      bodyBg:              '#F8FAF8',
      headerBg:            '#FFFFFF',
      headerColor:         '#0F172A',
      siderBg:             '#052005',
      footerBg:            '#F8FAF8',
      triggerBg:           CEM_DARK,
      triggerColor:        '#FFFFFF',
    },
    Drawer: {
      footerPaddingBlock:  16,
      footerPaddingInline: 24,
    },
    Modal: {
      borderRadiusLG:      20,
      headerBg:            '#FFFFFF',
      contentBg:           '#FFFFFF',
      footerBg:            '#FFFFFF',
      titleColor:          '#0F172A',
      titleFontSize:       18,
    },
    Form: {
      labelColor:          '#334155',
      labelFontSize:       14,
      labelRequiredMarkColor: '#DC2626',
      itemMarginBottom:    20,
      verticalLabelPadding: '0 0 6px',
    },
    Tabs: {
      itemColor:           '#64748B',
      itemSelectedColor:   CEM_GREEN,
      itemHoverColor:      CEM_DARK,
      inkBarColor:         CEM_GREEN,
      horizontalItemPadding: '12px 4px',
    },
    Pagination: {
      itemActiveBg:        '#E8F5E8',
      itemActiveColor:     CEM_DARK,
      itemActiveColorHover:CEM_GREEN,
      itemSize:            36,
      itemSizeSM:          28,
    },
    Alert: {
      defaultPadding:      '12px 16px',
      withDescriptionPadding: '16px 20px',
      withDescriptionIconSize: 22,
    },
    Result: {
      titleFontSize:       24,
      subtitleFontSize:    15,
      iconFontSize:        64,
      extraMargin:         '28px 0 0',
    },
    Statistic: {
      titleFontSize:       14,
      contentFontSize:     28,
    },
    Steps: {
      iconSize:            36,
      iconSizeSM:          28,
      iconFontSize:        16,
      dotSize:             10,
      dotCurrentSize:      12,
      navArrowColor:       '#94A3B8',
    },
    Upload: {
      actionsColor:        CEM_GREEN,
      pictureCardSize:     112,
    },
    DatePicker: {
      activeBorderColor:   CEM_GREEN,
      hoverBorderColor:    CEM_GREEN,
      activeShadow:        `0 0 0 2px ${CEM_GREEN}30`,
      cellHoverBg:         '#F0FDF4',
      cellActiveWithRangeBg: '#E8F5E8',
      cellHoverWithRangeBg: '#DCF0DC',
      cellRangeBorderColor:CEM_GREEN,
      cellHeight:          28,
    },
    Dropdown: {
      paddingBlock:        8,
    },
    Badge: {
      indicatorHeight:     20,
      indicatorHeightSM:   16,
      dotSize:             8,
      statusSize:          8,
      textFontWeight:      600,
    },
    Progress: {
      defaultColor:        CEM_GREEN,
      remainingColor:      '#E2E8F0',
      circleTextColor:     '#0F172A',
      lineBorderRadius:    999,
    },
    Tag: {
      borderRadiusSM:      20,
    },
    Notification: {
      width:               320,
    },
  },
}

export const darkTheme: ThemeConfig = {
  algorithm: theme.darkAlgorithm,
  token: {
    colorPrimary:        CEM_GREEN,
    colorSuccess:        '#10B981',
    colorWarning:        CEM_YELLOW,
    colorError:          '#EF4444',
    colorInfo:           '#3B82F6',
    colorLink:           '#4ADE80',
    colorLinkHover:      '#86EFAC',
    colorBgLayout:       '#071207',
    colorBgContainer:    '#102010',
    colorBgElevated:     '#172A17',
    colorBorder:         '#334B33',
    colorBorderSecondary:'#263B26',
    borderRadius:        10,
    borderRadiusLG:      20,
    borderRadiusSM:      8,
    fontFamily:          FONT_FAMILY,
    fontSize:            14,
    fontSizeHeading3:    24,
    fontWeightStrong:    600,
    lineHeight:          1.5,
    controlHeight:       44,
    controlHeightLG:     48,
    controlHeightSM:     36,
    controlOutline:      'rgba(74, 222, 128, 0.24)',
    boxShadow:           '0 4px 16px rgba(0, 0, 0, 0.28)',
    boxShadowSecondary:  '0 12px 32px rgba(0, 0, 0, 0.4)',
  },
  components: {
    Button: {
      primaryColor: '#FFFFFF',
      fontWeight:   600,
      paddingInline: 18,
    },
    Menu: {
      itemBg:              'transparent',
      itemColor:           'rgba(255,255,255,0.7)',
      itemHoverColor:      '#FFFFFF',
      itemSelectedColor:   CEM_DARK,
      itemSelectedBg:      CEM_YELLOW,
      darkItemSelectedBg:  CEM_YELLOW,
      darkItemSelectedColor: CEM_DARK,
    },
    Input: {
      activeBorderColor:   CEM_GREEN,
      hoverBorderColor:    CEM_GREEN,
      activeShadow:        `0 0 0 2px ${CEM_GREEN}30`,
    },
    Select: {
      optionSelectedBg:    '#1A3D1A',
    },
    Table: {
      headerBg:            '#1E293B',
      headerColor:         '#E2E8F0',
      rowHoverBg:          '#1A3D1A',
      rowSelectedBg:       '#214821',
      rowSelectedHoverBg:  '#285528',
      borderColor:         '#334B33',
      cellPaddingBlock:    14,
      cellPaddingInline:   16,
      headerBorderRadius:  12,
    },
    Card: {
      headerBg:            '#102010',
      headerFontSize:      16,
      headerHeight:        56,
      bodyPadding:         24,
      headerPadding:       24,
      actionsBg:           '#102010',
      extraColor:          '#94A3B8',
    },
    Layout: {
      bodyBg:              '#071207',
      headerBg:            '#102010',
      headerColor:         '#F8FAFC',
      siderBg:             '#031003',
      footerBg:            '#071207',
      triggerBg:           CEM_DARK,
      triggerColor:        '#FFFFFF',
    },
    Drawer: {
      footerPaddingBlock:  16,
      footerPaddingInline: 24,
    },
    Modal: {
      borderRadiusLG:      20,
      headerBg:            '#102010',
      contentBg:           '#102010',
      footerBg:            '#102010',
      titleColor:          '#F8FAFC',
      titleFontSize:       18,
    },
    Form: {
      labelColor:          '#CBD5E1',
      labelFontSize:       14,
      labelRequiredMarkColor: '#F87171',
      itemMarginBottom:    20,
      verticalLabelPadding: '0 0 6px',
    },
    Tabs: {
      itemColor:           '#94A3B8',
      itemSelectedColor:   '#4ADE80',
      itemHoverColor:      '#86EFAC',
      inkBarColor:         '#4ADE80',
      horizontalItemPadding: '12px 4px',
    },
    Pagination: {
      itemActiveBg:        '#1A3D1A',
      itemActiveColor:     '#86EFAC',
      itemActiveColorHover:'#4ADE80',
      itemSize:            36,
      itemSizeSM:          28,
    },
    Alert: {
      defaultPadding:      '12px 16px',
      withDescriptionPadding: '16px 20px',
      withDescriptionIconSize: 22,
    },
    Result: {
      titleFontSize:       24,
      subtitleFontSize:    15,
      iconFontSize:        64,
      extraMargin:         '28px 0 0',
    },
    Statistic: {
      titleFontSize:       14,
      contentFontSize:     28,
    },
    Steps: {
      iconSize:            36,
      iconSizeSM:          28,
      iconFontSize:        16,
      dotSize:             10,
      dotCurrentSize:      12,
      navArrowColor:       '#64748B',
    },
    Upload: {
      actionsColor:        '#4ADE80',
      pictureCardSize:     112,
    },
    DatePicker: {
      activeBorderColor:   '#4ADE80',
      hoverBorderColor:    '#4ADE80',
      activeShadow:        '0 0 0 2px rgba(74, 222, 128, 0.24)',
      cellHoverBg:         '#1A3D1A',
      cellActiveWithRangeBg: '#214821',
      cellHoverWithRangeBg: '#285528',
      cellRangeBorderColor:'#4ADE80',
      cellHeight:          28,
    },
    Dropdown: {
      paddingBlock:        8,
    },
    Badge: {
      indicatorHeight:     20,
      indicatorHeightSM:   16,
      dotSize:             8,
      statusSize:          8,
      textFontWeight:      600,
    },
    Progress: {
      defaultColor:        '#4ADE80',
      remainingColor:      '#334B33',
      circleTextColor:     '#F8FAFC',
      lineBorderRadius:    999,
    },
    Notification: {
      width: 320,
    },
  },
}

// Thème sombre canonique de tout l'espace authentifié.
const DASHBOARD_FONT = "'Inter', system-ui, sans-serif"

export const dashboardTheme: ThemeConfig = {
  algorithm: theme.darkAlgorithm,
  token: {
    colorPrimary:         '#2ECC71',
    colorSuccess:         '#22C55E',
    colorWarning:         '#FACC15',
    colorError:           '#EF4444',
    colorInfo:            '#2ECC71',
    colorBgBase:          '#07120D',
    colorBgLayout:        '#07120D',
    colorBgContainer:     '#0E1C16',
    colorBgElevated:      '#13261E',
    colorBorder:          'rgba(255,255,255,.06)',
    colorBorderSecondary: 'rgba(255,255,255,.04)',
    colorTextBase:        '#FFFFFF',
    colorTextSecondary:   '#94A3B8',
    borderRadius:         14,
    borderRadiusLG:       20,
    borderRadiusSM:       10,
    fontFamily:           DASHBOARD_FONT,
    fontSize:             15,
    fontSizeHeading3:     20,
    fontWeightStrong:     600,
    controlHeight:        46,
    controlHeightLG:      50,
    controlHeightSM:      38,
    controlOutline:       'rgba(46,204,113,.24)',
    boxShadow:            '0 8px 30px rgba(0,0,0,.25)',
    boxShadowSecondary:   '0 20px 40px rgba(0,0,0,.35)',
  },
  components: {
    Card: {
      colorBgContainer: '#0E1C16',
      headerBg:         '#0E1C16',
      headerFontSize:   20,
      headerHeight:     64,
      bodyPadding:      24,
      headerPadding:    24,
      actionsBg:        '#13261E',
      extraColor:       '#94A3B8',
      borderRadiusLG:   20,
    },
    Button: {
      borderRadius:        14,
      primaryColor:        '#07120D',
      defaultBg:           '#13261E',
      defaultBorderColor:  'rgba(255,255,255,.10)',
      defaultColor:        '#FFFFFF',
      defaultShadow:       '0 6px 18px rgba(0,0,0,.20)',
      fontWeight:          600,
      paddingInline:       18,
    },
    Menu: {
      itemBg:            'transparent',
      itemColor:         'rgba(255,255,255,.65)',
      itemHoverColor:    '#FFFFFF',
      itemHoverBg:       'rgba(255,255,255,.04)',
      itemSelectedBg:    'rgba(46,204,113,.14)',
      itemSelectedColor: '#FFFFFF',
      subMenuItemBg:     'transparent',
      darkItemBg:        '#081A12',
      darkItemColor:     'rgba(255,255,255,.65)',
      darkItemHoverBg:   'rgba(255,255,255,.04)',
      darkItemHoverColor:'#FFFFFF',
      darkItemSelectedBg:'rgba(46,204,113,.14)',
      darkItemSelectedColor: '#FFFFFF',
    },
    Select: {
      colorBgContainer:  '#0E1C16',
      colorBgElevated:   '#13261E',
      optionSelectedBg:  'rgba(46,204,113,.16)',
      optionActiveBg:    'rgba(255,255,255,.05)',
      activeBorderColor: '#2ECC71',
      hoverBorderColor:  '#2ECC71',
      activeOutlineColor:'rgba(46,204,113,.16)',
      borderRadius:      14,
    },
    Input: {
      colorBgContainer:  '#0E1C16',
      activeBorderColor: '#2ECC71',
      hoverBorderColor:  '#2ECC71',
      activeShadow:      '0 0 0 3px rgba(46,204,113,.16)',
      borderRadius:      14,
    },
    Table: {
      headerBg:            '#13261E',
      headerColor:         '#FFFFFF',
      rowHoverBg:          'rgba(255,255,255,.04)',
      rowSelectedBg:       'rgba(46,204,113,.12)',
      rowSelectedHoverBg:  'rgba(46,204,113,.16)',
      borderColor:         'rgba(255,255,255,.06)',
      cellPaddingBlock:    16,
      cellPaddingInline:   18,
      headerBorderRadius:  18,
    },
    Progress: {
      defaultColor:    '#2ECC71',
      remainingColor:  'rgba(255,255,255,.08)',
      circleTextColor: '#FFFFFF',
      lineBorderRadius: 999,
    },
    Statistic: {
      titleFontSize:    13,
      contentFontSize:  36,
    },
    Segmented: {
      trackBg:           'rgba(255,255,255,.04)',
      itemSelectedBg:    'rgba(46,204,113,.16)',
      itemColor:         '#94A3B8',
      itemSelectedColor: '#FFFFFF',
    },
    Badge: {
      indicatorHeight:   20,
      indicatorHeightSM: 16,
      dotSize:           8,
      statusSize:        8,
      textFontWeight:    600,
    },
    Tooltip: {
      colorBgSpotlight: '#13261E',
      colorTextLightSolid: '#FFFFFF',
      borderRadius:      10,
    },
    Modal: {
      borderRadiusLG: 20,
      headerBg:       '#0E1C16',
      contentBg:      '#0E1C16',
      footerBg:       '#0E1C16',
      titleColor:     '#FFFFFF',
      titleFontSize:  18,
    },
    Form: {
      labelColor:             '#FFFFFF',
      labelFontSize:          14,
      labelRequiredMarkColor: '#EF4444',
      itemMarginBottom:       20,
      verticalLabelPadding:   '0 0 6px',
    },
    Tabs: {
      itemColor:             '#94A3B8',
      itemSelectedColor:     '#2ECC71',
      itemHoverColor:        '#FFFFFF',
      inkBarColor:           '#2ECC71',
      horizontalItemPadding: '12px 4px',
    },
    Pagination: {
      itemActiveBg:         'rgba(46,204,113,.16)',
      itemActiveColor:      '#FFFFFF',
      itemActiveColorHover: '#FFFFFF',
      itemSize:             38,
      itemSizeSM:           30,
    },
    Drawer: {
      colorBgElevated:     '#0E1C16',
      footerPaddingBlock:  16,
      footerPaddingInline: 24,
    },
    Layout: {
      bodyBg:       '#07120D',
      headerBg:     '#081A12',
      headerColor:  '#FFFFFF',
      siderBg:      '#081A12',
      footerBg:     '#07120D',
      triggerBg:    '#13261E',
      triggerColor: '#FFFFFF',
    },
    Tag: {
      defaultBg:      'rgba(255,255,255,.06)',
      defaultColor:   '#FFFFFF',
      borderRadiusSM: 999,
    },
    Dropdown: {
      colorBgElevated: '#13261E',
      paddingBlock:    8,
    },
    Alert: {
      defaultPadding:          '12px 16px',
      withDescriptionPadding:  '16px 20px',
      withDescriptionIconSize: 22,
    },
    Result: {
      titleFontSize:    24,
      subtitleFontSize: 15,
      iconFontSize:     64,
      extraMargin:      '28px 0 0',
    },
    Steps: {
      iconSize:       36,
      iconSizeSM:     28,
      iconFontSize:   16,
      dotSize:        10,
      dotCurrentSize: 12,
      navArrowColor:  '#94A3B8',
    },
    Upload: {
      actionsColor:    '#2ECC71',
      pictureCardSize: 112,
    },
    DatePicker: {
      activeBorderColor:     '#2ECC71',
      hoverBorderColor:      '#2ECC71',
      activeShadow:          '0 0 0 3px rgba(46,204,113,.16)',
      cellHoverBg:           'rgba(255,255,255,.05)',
      cellActiveWithRangeBg: 'rgba(46,204,113,.16)',
      cellHoverWithRangeBg:  'rgba(46,204,113,.10)',
      cellRangeBorderColor:  '#2ECC71',
      cellHeight:            32,
    },
    Switch: {
      colorPrimary:      '#2ECC71',
      colorPrimaryHover: '#22C55E',
      handleBg:          '#FFFFFF',
    },
    Notification: {
      colorBgElevated: '#13261E',
      width:            360,
    },
  },
}

// Variante claire du thème canonique de l'espace authentifié (toggle clair/sombre).
export const dashboardThemeLight: ThemeConfig = {
  algorithm: theme.defaultAlgorithm,
  token: {
    colorPrimary:         '#1A6B1A',
    colorSuccess:         '#15803D',
    colorWarning:         '#92400E',
    colorError:           '#DC2626',
    colorInfo:            '#1A6B1A',
    colorBgBase:          '#F8FAF8',
    colorBgLayout:        '#F8FAF8',
    colorBgContainer:     '#FFFFFF',
    colorBgElevated:      '#FFFFFF',
    colorBorder:          'rgba(15,23,42,.08)',
    colorBorderSecondary: 'rgba(15,23,42,.05)',
    colorTextBase:        '#0F172A',
    colorTextSecondary:   '#64748B',
    borderRadius:         14,
    borderRadiusLG:       20,
    borderRadiusSM:       10,
    fontFamily:           DASHBOARD_FONT,
    fontSize:             15,
    fontSizeHeading3:     20,
    fontWeightStrong:     600,
    controlHeight:        46,
    controlHeightLG:      50,
    controlHeightSM:      38,
    controlOutline:       'rgba(26,107,26,.16)',
    boxShadow:            '0 1px 2px rgba(15,23,42,.04), 0 8px 24px rgba(15,23,42,.08)',
    boxShadowSecondary:   '0 4px 10px rgba(15,23,42,.06), 0 20px 40px rgba(15,23,42,.10)',
  },
  components: {
    Card: {
      colorBgContainer: '#FFFFFF',
      headerBg:         '#FFFFFF',
      headerFontSize:   20,
      headerHeight:     64,
      bodyPadding:      24,
      headerPadding:    24,
      actionsBg:        '#F1F4F2',
      extraColor:       '#64748B',
      borderRadiusLG:   20,
    },
    Button: {
      borderRadius:        14,
      primaryColor:        '#FFFFFF',
      defaultBg:           '#F1F4F2',
      defaultBorderColor:  'rgba(15,23,42,.10)',
      defaultColor:        '#0F172A',
      defaultShadow:       '0 2px 6px rgba(15,23,42,.05)',
      fontWeight:          600,
      paddingInline:       18,
    },
    Menu: {
      itemBg:            'transparent',
      itemColor:         'rgba(15,23,42,.65)',
      itemHoverColor:    '#0F172A',
      itemHoverBg:       'rgba(15,23,42,.04)',
      itemSelectedBg:    'rgba(26,107,26,.10)',
      itemSelectedColor: '#0F172A',
      subMenuItemBg:     'transparent',
      darkItemBg:        '#FFFFFF',
      darkItemColor:     'rgba(15,23,42,.65)',
      darkItemHoverBg:   'rgba(15,23,42,.04)',
      darkItemHoverColor:'#0F172A',
      darkItemSelectedBg:'rgba(26,107,26,.10)',
      darkItemSelectedColor: '#0F172A',
    },
    Select: {
      colorBgContainer:  '#FFFFFF',
      colorBgElevated:   '#FFFFFF',
      optionSelectedBg:  'rgba(26,107,26,.10)',
      optionActiveBg:    'rgba(15,23,42,.04)',
      activeBorderColor: '#1A6B1A',
      hoverBorderColor:  '#1A6B1A',
      activeOutlineColor:'rgba(26,107,26,.16)',
      borderRadius:      14,
    },
    Input: {
      colorBgContainer:  '#FFFFFF',
      activeBorderColor: '#1A6B1A',
      hoverBorderColor:  '#1A6B1A',
      activeShadow:      '0 0 0 3px rgba(26,107,26,.14)',
      borderRadius:      14,
    },
    Table: {
      headerBg:            '#F1F4F2',
      headerColor:         '#0F172A',
      rowHoverBg:          'rgba(15,23,42,.03)',
      rowSelectedBg:       'rgba(26,107,26,.08)',
      rowSelectedHoverBg:  'rgba(26,107,26,.12)',
      borderColor:         'rgba(15,23,42,.08)',
      cellPaddingBlock:    16,
      cellPaddingInline:   18,
      headerBorderRadius:  18,
    },
    Progress: {
      defaultColor:    '#1A6B1A',
      remainingColor:  'rgba(15,23,42,.08)',
      circleTextColor: '#0F172A',
      lineBorderRadius: 999,
    },
    Statistic: {
      titleFontSize:    13,
      contentFontSize:  36,
    },
    Segmented: {
      trackBg:           'rgba(15,23,42,.05)',
      itemSelectedBg:    '#FFFFFF',
      itemColor:         '#64748B',
      itemSelectedColor: '#0F172A',
    },
    Badge: {
      indicatorHeight:   20,
      indicatorHeightSM: 16,
      dotSize:           8,
      statusSize:        8,
      textFontWeight:    600,
    },
    Tooltip: {
      colorBgSpotlight: '#0F172A',
      colorTextLightSolid: '#FFFFFF',
      borderRadius:      10,
    },
    Modal: {
      borderRadiusLG: 20,
      headerBg:       '#FFFFFF',
      contentBg:      '#FFFFFF',
      footerBg:       '#FFFFFF',
      titleColor:     '#0F172A',
      titleFontSize:  18,
    },
    Form: {
      labelColor:             '#0F172A',
      labelFontSize:          14,
      labelRequiredMarkColor: '#DC2626',
      itemMarginBottom:       20,
      verticalLabelPadding:   '0 0 6px',
    },
    Tabs: {
      itemColor:             '#64748B',
      itemSelectedColor:     '#1A6B1A',
      itemHoverColor:        '#0F172A',
      inkBarColor:           '#1A6B1A',
      horizontalItemPadding: '12px 4px',
    },
    Pagination: {
      itemActiveBg:         'rgba(26,107,26,.10)',
      itemActiveColor:      '#0F172A',
      itemActiveColorHover: '#0F172A',
      itemSize:             38,
      itemSizeSM:           30,
    },
    Drawer: {
      colorBgElevated:     '#FFFFFF',
      footerPaddingBlock:  16,
      footerPaddingInline: 24,
    },
    Layout: {
      bodyBg:       '#F8FAF8',
      headerBg:     '#FFFFFF',
      headerColor:  '#0F172A',
      siderBg:      '#FFFFFF',
      footerBg:     '#F8FAF8',
      triggerBg:    '#F1F4F2',
      triggerColor: '#0F172A',
    },
    Tag: {
      defaultBg:      'rgba(15,23,42,.05)',
      defaultColor:   '#0F172A',
      borderRadiusSM: 999,
    },
    Dropdown: {
      colorBgElevated: '#FFFFFF',
      paddingBlock:    8,
    },
    Alert: {
      defaultPadding:          '12px 16px',
      withDescriptionPadding:  '16px 20px',
      withDescriptionIconSize: 22,
    },
    Result: {
      titleFontSize:    24,
      subtitleFontSize: 15,
      iconFontSize:     64,
      extraMargin:      '28px 0 0',
    },
    Steps: {
      iconSize:       36,
      iconSizeSM:     28,
      iconFontSize:   16,
      dotSize:        10,
      dotCurrentSize: 12,
      navArrowColor:  '#64748B',
    },
    Upload: {
      actionsColor:    '#1A6B1A',
      pictureCardSize: 112,
    },
    DatePicker: {
      activeBorderColor:     '#1A6B1A',
      hoverBorderColor:      '#1A6B1A',
      activeShadow:          '0 0 0 3px rgba(26,107,26,.14)',
      cellHoverBg:           'rgba(15,23,42,.04)',
      cellActiveWithRangeBg: 'rgba(26,107,26,.12)',
      cellHoverWithRangeBg:  'rgba(26,107,26,.08)',
      cellRangeBorderColor:  '#1A6B1A',
      cellHeight:            32,
    },
    Switch: {
      colorPrimary:      '#1A6B1A',
      colorPrimaryHover: '#15803D',
      handleBg:          '#FFFFFF',
    },
    Notification: {
      colorBgElevated: '#FFFFFF',
      width:            360,
    },
  },
}
